version: '3'

services:
###> doctrine/doctrine-bundle ###
  nginx-service:
    image: nginx:stable-alpine
    container_name: intime-nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/project # changed
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-service # changed
      - database
    networks:
      - nginx-php-postgres # changed
  
  # changed
  php-service:
    tty: true
    build:
      context: .
      dockerfile: ./Dockerfile # changed
    container_name: intime-php
    ports:
      - "9000:9000"
    volumes:
      - ./:/var/www/project # changed
    networks:
      - nginx-php-postgres # changed

  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    container_name: intime-postgres
    environment:
      POSTGRES_DB: "mahjong"
      # You should definitely change the password in production
      POSTGRES_PASSWORD: "root"
      POSTGRES_USER: "root"
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "mahjong", "-U", "root"]
      timeout: 5s
      retries: 5
      start_period: 60s
    ports:
      - "5432:5432"
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    networks:
      - nginx-php-postgres
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
networks:
    nginx-php-postgres:
